---
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    enabled: false
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 600
  method-count:
    config:
      threshold: 35
  method-lines:
    config:
      threshold: 500
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 30
  similar-code:
    enabled: false
engines:
  duplication:
    enabled: true
    config:
      languages:
        - typescript
  eslint:
    enabled: true
    channel: eslint-8
  fixme:
    enabled: true
ratings:
  paths:
    - "*.ts"
    - "test/*.ts"
