---
checks:
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 100
  method-count:
    config:
      threshold: 35
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 30
  similar-code:
    config:
      threshold: 60
engines:
  duplication:
    enabled: true
    config:
      languages:
        - typescript
  eslint:
    enabled: true
    channel: eslint-8
  fixme:
    enabled: true
ratings:
  paths:
    - "*.ts"
    - "test/*.ts"
